---
title: "DAGPD: Niche-Dependent AMGs within Various Domestic"
author: "Yuxuan Huang"
format: 
  html:
    embed-resources: true
---

# Niche-Dependent AMGs within Various Domestic

## A bar plot showing alpha diversity of CAZy in phages among domestic animals

```{r,warning=FALSE,message=FALSE}
setwd("~/Downloads/DAGPD/cell/Scripts")
library(tidyverse)
source("./theme_llm.R")
theme_set(theme_llm(base_size = 16,legend = "top"))

cazy_alpha <- read.table("../Pre-processed_Files/cazy_alpha.txt",header = T)
cazy_alpha$Category <- factor(cazy_alpha$Category,levels = rev(unique(cazy_alpha$Category)))
theme_set(theme_llm(base_size = 16,legend = "right"))
ggplot()+geom_col(data=cazy_alpha,mapping = aes(x=Sources,y=Counts,fill=Category),width=0.5)+scale_fill_brewer(palette = "Set3")+
  ylab("Cazymes Diversity")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## A bar plot showing number of CAZy per 1000 gene
```{r,warning=FALSE,message=FALSE}
cazy <- read.table("../Pre-processed_Files/cazy.txt",header = T)
cazy$Category <- factor(cazy$Category,levels = rev(unique(cazy$Category)))
theme_set(theme_llm(base_size = 16,legend = "right"))
ggplot()+geom_col(data=cazy,mapping = aes(x=Sources,y=Counts/Ratio,fill=Category),width=0.5)+scale_fill_brewer(palette = "Set3")+
  ylab("Cazymes per 1000 genes")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## A bar plot showing percent of CAZy subfamily among different domestic animals
```{r,warning=FALSE,message=FALSE}
cazy_percent <- read.table("../Pre-processed_Files/cazy_percent.txt",header = T)
cazy_percent$Category <- factor(cazy_percent$Category,levels = c("GH25","GH23","GH24","GH108", "GT2", "GH73", "GT51", "GT4","GH19", "CBM50","GH13", "GH2", "GH43","Others"))

theme_set(theme_llm(base_size = 16,legend = "right"))

ggplot()+
  geom_col(data=cazy_percent,mapping = aes(x=Sources,y=Percent,fill=Category),width = 0.5)+
scale_color_manual(values  = c("GH24"="#4472C4","GH25"="#ED7D31","GT2"="#997300","GH13"="#70AD47",
  "GH2"="#00A161","GH73"="#FFC000","GT4"="#5B9BD5","GH43"="#9E480E","GH108"="#AE2AFF","GH23"="#2E90FF","GH19"="#D4FF43","CBM50"="#261FAB","GT51"="#D03500","Others"="lightgrey"),
                   aesthetics = c("fill"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
